Update README.md
ivokub/tailscale-qpkg pull request #31
Opened 2022-02-09 12:53 UTC by ajnadox

Added update to new version info.

2022-03-09 17:02 UTC, ajnadox commented
@ivokub would you be kind to merge this update also :)?

2022-05-23 09:50 UTC, ajnadox commented
@ivokub this is still not merged, will you fix :) ? thanks!

2022-06-08 20:54 UTC, ivokub commented
Thanks @ajnadox, I'll have a look and merge if possible.

2022-06-08 21:08 UTC, ivokub requested changes
I think the pull request makes sense in general. However, I generalized the new section for both UNIX/Windows build targets and specified that the service restarts automatically.

On another note -- please rebase on top of current master branch. There are few updates in the version numbers.

2022-06-08 21:08 UTC, ivokub commented on README.md
> +
```suggestion
Updating
--------

When Tailscale package is already installed, then it is sufficient to install only a new version of Tailscale package in QNAP App Center. The service will restart automatically and use current configuration.

To build new package manually, rerun the commands for corresponding target (UNIX or Windows) in the updated repository.

```

2022-09-22 11:54 UTC, closed without merging

2022-09-22 11:54 UTC, ajnadox commented
rebase on top of current master branch